name: Build Report
on:
  push:
    branches:
      # Run only on pushes to report
      - report
  schedule:
    # Run every day at 9am UTC.
    # * is a special character in YAML so you have to quote this string
    - cron:  '0 9 * * *'
  workflow_dispatch:
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout CSS Audit
      uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
  
    - name: Checkout WordPress Core
      uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      with:
        repository: WordPress/wordpress-develop
        path: wordpress

    - name: Use Node.js
      uses: actions/setup-node@3235b876344d2a9aa001b8d1453c930bba69e610 # v3.9.1
      with:
        node-version-file: ".nvmrc"
        cache: "npm"

    - name: Install dependencies
      run: npm install

    - name: Build the audit report
      run: npm run css-audit -- wordpress/src/wp-admin/css/*.css wordpress/src/wp-includes/css/*.css

    - name: Remove WordPress files
      run: rm -rf wordpress

    - name: Commit and push
      uses: actions-js/push@5a7cbd780d82c0c937b5977586e641b2fd94acc5 # 1.5
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        message: "[Automated] Update report"
        branch: "report"
        rebase: true
