name: Merge trunk into report branch
on:
  push:
    branches:
      # Run on pushes to trunk
      - 'trunk'
  workflow_dispatch:
jobs:
  merge-branch:
    runs-on: ubuntu-latest
    steps:
      # Set config to ignore conflicts in /public
      # specified in .gitattributes
      - run: git config merge.ours.driver true
      - uses: actions/checkout@v2
      - name: Merge trunk -> report
        uses: devmasx/merge-branch@v1.3.1
        with:
          type: now
          target_branch: report
          github_token: ${{ secrets.GITHUB_TOKEN }}
